/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */

import food from './modules/food';

export default {
  'food': food['food']
};

/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */