/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */
require('angular');



export default {
  'nutrients': angular.module('nutrients', [])
    .directive('nutrient',                    require('./directives/nutrient'))


};
/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */